name: Deploy PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install dependencies and build
        if: github.event.action != 'closed'
        run: |
          npm ci
          npm run build -- --base=/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.number }}/
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887
        with:
          source-dir: ./dist
          comment: true
